spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal_blog?serverTimezone=UTC
    username: root
    password: zw2635879218
    driver-class-name: com.mysql.cj.jdbc.Driver
  #开启HiddenHttpMethodFilter解析put和delete请求
  mvc:
    hiddenmethod:
      filter:
        enabled: true


#MyBatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
